### ISSUE TITLE
Stations UI could be hidden on Phones with nodge

### ISSUE THREAD

**Issue by DanielPa** [Suplanus/Cuterdio#102]
...and maybe in settings view, too.
https://docs.microsoft.com/de-de/xamarin/xamarin-forms/platform/ios/page-safe-area-layout

**Comment by Suplanus** [comment]
This is hidden on nodge iPhones:
![image](https://user-images.githubusercontent.com/2002916/89003812-07f2c480-d301-11ea-95d0-20e0dba07bdf.png)
