### ISSUE TITLE
Open in Apple Music

### ISSUE THREAD

**Issue by Suplanus** [Suplanus/Cuterdio#12]
- [ ] Search-Url `Green Day Basket Case` >>> [`https://itunes.apple.com/search?term=green+day+basket+case&Entity=song&limit=1`](https://itunes.apple.com/search?term=green+day+basket+case&Entity=song&limit=1)
- [ ] Json parse e.g. `trackViewUrl`  >>> `https://music.apple.com/us/album/basket-case/1160081985?i=1160082180&uo=4`
- [ ] Create link with `geo`, `app`, `at`: https://affiliate.itunes.apple.com/resources/documentation/basic_affiliate_link_guidelines_for_the_phg_network/

**Comment by b-ongo** [comment]
This is one that would be great to have, especially Apple Music. 

Also in the song history section an add to library or playlist button would be double trouble!

**Comment by Suplanus** [comment]
Thanks!
Try to get it in the 1.5.
