### ISSUE TITLE
Station Bremen 4 (Four)

### ISSUE THREAD

**Issue by Seger85** [Suplanus/Cuterdio#181]
The station: Bremen 4 (Vier) has changed its streaming address, at least that's what the current stream says.

**Comment by Seger85** [comment]
https://www.bremenvier.de/livestream/livestream-bremenvier-100.html

**Comment by Seger85** [comment]
https://icecast.radiobremen.de/rb/bremenvier/live/mp3/128/stream.mp3 (verschlüsselt)

http://icecast.radiobremen.de/rb/bremenvier/live/mp3/128/stream.mp3 (unverschlüsselt)

**Comment by Suplanus** [comment]
Thank you.

But the database is from https://www.radio-browser.info/
They will remove the broken entries. Please add the stations in Cuterdio, so its also added there.

The station can also inform the database.
