### ISSUE TITLE
"Open in Apple Music"

### ISSUE THREAD

**Issue by goshpolly** [Suplanus/Cuterdio#189]
Would it be possible to open songs in Apple Music please, for those of us have subscribed to the native iOS music service? Ideally I would love to have other music services open to like Tidal and Qobuz. But I've got that would require a select box to take the services you want to see.

**Comment by Suplanus** [comment]
You can open in Music on the backside of the cover:
![image](https://user-images.githubusercontent.com/2002916/196339750-d7cfb132-47ac-4276-8d26-dc4403149945.png)

**Comment by goshpolly** [comment]
Strange, the Apple Music link seems to be absent sometimes or appear after some lag whereas Spotify is always there and immediately. Example just now: ![image](https://user-images.githubusercontent.com/29926846/197078195-93d7cf50-30a5-4f58-81c7-6a96f2ac8df8.png)

**Comment by Suplanus** [comment]
Apple Music, Wikipedia, Spotify, Cover is only available if the track was found on the services.
Spotify is loaded first, because of there are all informations (like album & cover).
