### ISSUE TITLE
Search seems broken

### ISSUE THREAD

**Issue by dansroot** [Suplanus/Cuterdio#205]
I recently discovered Cuterdio and I am already a big fan of it and purchsed several "extras". Until yesterday everything seemed to work fine and I could add new stations either through the search function or directly (if the URL is known).

But yesterday the search option (plus button, enter keyword) suddenly stopped to work. When entering any search item (like "80s"), the screen blinks shortly and then does nothing.

The same behaviour appears both on my iPhone (latest iOS 17.2.1) and on my iPad (17.1), where I just did a fresh install of Cuterdio today (haven't used it on that device yet).

Please have a look, thanks!

**Comment by Suplanus** [comment]
Should work now. Thanks for the report.
