### ISSUE TITLE
Loose/fuzzy interpreter name for determining covers

### ISSUE THREAD

**Issue by DanielPa** [Suplanus/Cuterdio#33]
e.g. interpreter name from radio stream is `Itchy Poopzkid`, which results in no match because Spotify has renamed the interpreter to `Itchy`

**Comment by Suplanus** [comment]
Thats crazy... Why???

It would be easy, when a search failed, to split the words and search again... But think this could be more `false positive` results... Example: 
`Iron Maiden` -> `Iron`

There are plans to do a second search if spotify fails on Apple Music... but the there is no easy way to do this. Perhaps "someone" would like to write a framework for .NET 🦄

**Comment by Suplanus** [comment]
![image](https://user-images.githubusercontent.com/2002916/73604993-f1112680-4598-11ea-9686-70a548c98775.png)

**Comment by Suplanus** [comment]
I made some improvements to the search. A fuzzy search is not supported.
The search in Spotify is nod that good... See here:
https://open.spotify.com/search/Manowar%20Warriors%20of%20the%20World

![image](https://user-images.githubusercontent.com/2002916/101896222-ed7f0080-3ba8-11eb-89e9-ed799e120cf2.png)

Its not possible to get the Image of the Track in the API.
