### ISSUE TITLE
Edit station

### ISSUE THREAD

**Issue by Suplanus** [Suplanus/Cuterdio#59]
- [ ] Edit
- [ ] Delete

**Comment by ParoTheParrot** [comment]
Hi there!
Sorry @Suplanus , but I can’t find the edit screen to delete a station. 😐

**Comment by Suplanus** [comment]
Hi, 

I know it's a little hidden. Edit the station with `>` and scroll to the bottom, there is a button.
I will bring back "Swipe to delete".
