### ISSUE TITLE
Volume control 

### ISSUE THREAD

**Issue by TUNER88** [Suplanus/Cuterdio#60]
Would be great to have the possibility to reduce the volume in the application.
Reducing the volume on the system level leads to reduced volume for messengers and other important notification sounds.

**Comment by Suplanus** [comment]
Thanks for the feedback.

A separate volume is an argument...
Will come in the next major versions 🦄

**Comment by TUNER88** [comment]
Awesome, thanks 🙇

**Comment by Suplanus** [comment]
Try to test this Nuget: https://c-sharx.net/forms-volumeslider
I think the best would be two volume sliders:
- System volume
- Cuterdio volume
