### ISSUE TITLE
Setting: Configurable album field for System- / Remote-Player

### ISSUE THREAD

**Issue by TUNER88** [Suplanus/Cuterdio#74]
Let's make use of [MPRemoteCommandCenter](https://developer.apple.com/documentation/mediaplayer/mpremotecommandcenter), this will enable controls from lock screen and other remote sources, like steering wheel buttons while playing via bluetooth in the car.

What do you think about?

**Comment by Suplanus** [comment]
What commands should be possible?

**Comment by TUNER88** [comment]
Play/pause is already working, what I'm missing is the ability to switch stations without pulling the phone while driving a car.

I could imagine that some users would be happy to do it via the headset buttons while jogging for example.

![IMG_0103](https://user-images.githubusercontent.com/1565397/82314127-9c6bad00-99c9-11ea-81fa-46b64c9354cf.png)

**Comment by TUNER88** [comment]
I would also appreciate the current station name on the lockscreen.

**Comment by megaholti** [comment]
Yeah I want it to! Both station name and navigate true stations - it is much easier to navigate if CarPlay ist available.

**Comment by Suplanus** [comment]
Carplay is on the way. You can test it in the beta version. Download it [here](https://cuterdio.com/download).

**Comment by Suplanus** [comment]
Station in lockscreen:
I think the problem is there is no space for the station. I have to place it to the artist-album field and it would be too long:
![image](https://user-images.githubusercontent.com/2002916/82748562-386b2f00-9da3-11ea-8291-4086acee1b0d.png)

**Comment by megaholti** [comment]
Ja ich hatte es schon getestet. Freu mich voll. Allerdings wenn ich eine Station starte, dann springt er nicht in den musikbildschirm, sondern zurück in die stationübersicht.

Der Wechsel zwischen den Stationen wäre wirklich schön. Genauso würde ich mir wünschen den stationnamen, wenn es nicht klappt den stationsnamen beim Album mit anzuzeigen, könnte es doch wenigstens beim CarPlay oben links oder rechts anzeigen zu lassen. Ich sende später Screenshots 

A. Holtfreter
Von meinem iPhone gesendet

**Comment by megaholti** [comment]
Anbei mein Screenshot, oben links wo jetzt der Appname steht, könnte doch stattdessen die Station eingeblendet werden, ich habe auch schon CarPlay Apps gesehen, welche rechts oben einen individuellen Text stehen hatten.





A. Holtfreter
Von meinem iPhone gesendet

**Comment by Suplanus** [comment]
Leider sieht man den Screenshot nicht wenn du per Email auf das Ticket antwortest. Bitte direkt bei GitHub hochladen.

**Comment by TUNER88** [comment]
![IMG_0121](https://user-images.githubusercontent.com/1565397/82814929-65e5d480-9e98-11ea-996c-444948186b80.PNG)
![IMG_1D1A8F02CD64-1](https://user-images.githubusercontent.com/1565397/82815519-a2fe9680-9e99-11ea-825d-f1f7ed45f32e.jpeg)
I've checked some other radio applications and found that most of them are showing the station name in the upper cell and combined "artist - title" label in the lower cell.

I would prefer the same setup, or at least some config options to configure it. I don't think that long labels are really a issue since they are autoscrolled by default.

Furthermore there seems to be some streaming attribute that is placing "Live" label on the progress bar.

**Comment by megaholti** [comment]
Das ist keine gute Lösung, da der Song ja ausgelesen wird. Das geht mit dem beschriebenen Setup nicht. 

So finde ich es nicht gut. Bitte auf keinen Fall so umsetzen! Artist gehört zu artist und Song zu Song!

A. Holtfreter
Von meinem iPhone gesendet

**Comment by TUNER88** [comment]
Is just a pragmatic solution to display more data, as far as I know most AVRCP capable devices supporting only 3 meta fields: "Track", "Album" and "Artist". But we want to show an additional station name.

I would also be fine with some config toggle like "Display station instead of Album".

Common fields:
![screen-shot-2011-06-09-at-9 01 12-am-670x370](https://user-images.githubusercontent.com/1565397/82828945-7440ea00-9eb2-11ea-82a4-c6feeab93ea9.png)

@megaholti I don't get your problem with the concatenation, could you please describe it in detail?

**Comment by Suplanus** [comment]
A setting would be a compromise that I can build in. But I would not replace a field...
Would be this setting OK?
`Append station name in the album field for remote player`

This setting would be affect to the notification center player on the iPhone and also for bluetooth devices.

**Comment by megaholti** [comment]
Hi for CarPlay you can place the station name in the upper left (now Cuterdio standsichre on) or the Upper Right (nothing is showing) 
![120508F7-E619-4412-9903-A87B3F6DE0F2](https://user-images.githubusercontent.com/65846070/82865734-c3753200-9f27-11ea-82f6-5b20ad4b62c8.jpeg)

**Comment by Suplanus** [comment]
The now playing screen is a fixed control which can not be modified.
So the upper left is always the app name and upper right is empty space.

**Comment by megaholti** [comment]
Ok but in some apps it shows favorites or back instead of Cuterdio so it must be changeable

A. Holtfreter
Von meinem iPhone gesendet

**Comment by Suplanus** [comment]
>so it must be changeable
Yes but only you are navigating from a folder. But it not possible to make a folder for the radio station and there is only one element.

**Comment by megaholti** [comment]
Ok thanks. If it a reason to make a switch for changing album info to radio station info?

So I have my solution for CarPlay the tuner for his bt device and all the others can let it?!

2.) if it possible to display the station logo in CarPlay screen even no album Foto is available?

A. Holtfreter
Von meinem iPhone gesendet

**Comment by TUNER88** [comment]
We also could go with a select element instead of toggle to give a bit more flexibility.
I've following options in mind:

Display station name on remote device:
- off (default?)
- Instead of album
- Append to album
- Prepend to album
- ?

What do you think about it?

**Comment by megaholti** [comment]
Yeah sounds good. Thanks

A. Holtfreter
Von meinem iPhone gesendet

**Comment by Suplanus** [comment]
Sounds good, I turned this into feature and renamed it.
Let me know how important this issue is. And for beer I can code faster 😉

**Comment by megaholti** [comment]
Thanks you get a beer. But more important is the skip to the next favorite station! In CarPlay Dashboard I must now touch three times to change my station to another!

A. Holtfreter
Von meinem iPhone gesendet

**Comment by megaholti** [comment]
I will spend you a beer crate can you send a paypal adress?

A. Holtfreter
Von meinem iPhone gesendet

**Comment by Suplanus** [comment]
CarPlay: I have create here an Issue. Can you answer my question? #81 
Paypal: Write me an Email I will send you the address. Thanks 💕

**Comment by TUNER88** [comment]
@Suplanus your 🍺 is on the way, just have to replace the beta with the prod version again.
Remote control works seems to work, thank you so much.

The last point to make it perfect would be the `MPNowPlayingInfoPropertyIsLiveStream` flag on `nowPlayingInfo` replace the progresses bar with proper "live" label.

https://stackoverflow.com/q/53483705/13324363

**Comment by Suplanus** [comment]
@TUNER88: Thanks for the 🍺 

**Live**
I created an Issue for that: #83

**Comment by Suplanus** [comment]
# Implementation

Description: 
>Display station name in album field (lock screen, notification center, CarPlay, remote device)

Settings:
```
0. No
1. Instead
2. Prepend
3. Append
```

**Comment by megaholti** [comment]
Thanks! Great job!

A. Holtfreter
Von meinem iPhone gesendet
