### ISSUE TITLE
Crash on macOS 10.13 when opening menu

### ISSUE THREAD

**Issue by RalfMuc** [Suplanus/Cuterdio#85]
klick on settings icon -> app crash
macOS 10.13.6
cuterdio app-store version

**Comment by Suplanus** [comment]
Which icon do you mean?

**Comment by RalfMuc** [comment]
I hope you can fix the bug better with a beer :)

**Comment by Suplanus** [comment]
The hole life is better with beer 🍺
Thanks 🦄

**Comment by Suplanus** [comment]
The update is now on the app store.
I had to remove the volume slider in macOS 10.13...

**Comment by nowakommunikation** [comment]
Still crashing under High Sierra 10.13.6 with version 2.4.1 when opening the menu. Everything else seems to work. 
Menu opens fine without crashing under later macOS versions. Haven't tried all but unter Ventura no problems.
